import { reflections } from "./reflections_data.mjs";
import { writeFileSync } from "fs";

// These titles get display_order 0-5 (shown on the homepage), spanning all
// three categories. Everything else follows in file order.
const TOP_SIX = [
  "13 Years of Leadership Lessons from 'World's Best Boss'",
  "Why Most L&D Programmes Fail Before They Even Begin",
  "Not Everyone Should Be a Leader, and That's a Good Thing",
  "Forget Self-Love — Self-Awareness Is the Real Superpower",
  "Vipassana — The Trek of the Mind",
  "Gen Z Isn't the Problem — You Are",
];

function sqlEscape(str) {
  return (str || "").replace(/'/g, "''");
}

function deriveDescription(body) {
  const firstLine = body.split("\n")[0].trim();
  if (firstLine.length <= 150) return firstLine;
  const cut = firstLine.slice(0, 150);
  const lastSpace = cut.lastIndexOf(" ");
  return cut.slice(0, lastSpace) + "…";
}

const ordered = [
  ...TOP_SIX.map((t) => reflections.find((r) => r.title === t)),
  ...reflections.filter((r) => !TOP_SIX.includes(r.title)),
];

const missing = TOP_SIX.filter((t) => !reflections.find((r) => r.title === t));
if (missing.length) {
  console.error("Titles in TOP_SIX not found in data:", missing);
  process.exit(1);
}

const values = ordered
  .map((r, i) => {
    const description = deriveDescription(r.body);
    return `  ('${sqlEscape(r.category)}', '${sqlEscape(r.publication)}', '${sqlEscape(r.title)}', '${sqlEscape(description)}', '${sqlEscape(r.body)}', ${i})`;
  })
  .join(",\n");

const sql = `-- Bulk import of reflections from "Reflections .pdf".
-- Generated by scripts/generate_reflections_sql.mjs — do not hand-edit,
-- regenerate instead if the source content changes.
--
-- display_order 0-5 are the 6 pieces shown on the homepage; the rest appear
-- only on the "all reflections" page. Run this once in the Supabase SQL Editor.
--
-- Clears the 3 old placeholder rows (stale category scheme, short stub
-- copy written before the real Reflections doc was available) before
-- inserting the full, real set below.

delete from reflections;

insert into reflections (category, publication, title, description, body, display_order)
values
${values};
`;

writeFileSync(new URL("../supabase/006_bulk_reflections.sql", import.meta.url), sql);
console.log(`Wrote ${ordered.length} reflections to supabase/006_bulk_reflections.sql`);
